#!/usr/bin/env bash

if [[ "$1" == "" ]]; then
    echo "Usage: compute_sha <version>"
    exit 1
fi

# Strip leading 'v' if present
version="${1#v}"

curl -sL "https://github.com/joeygibson/jsonquill/archive/refs/tags/v${version}.tar.gz" | shasum -a 256

